version: '3.3'
services:
  sql:
    image: mysql:5.7
    ports:
      - '3306:3306'
    expose:
      - '3306'
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    volumes:
      - my-volume:/var/lib/mysql
    networks:
      - demo-net
    hostname: 'demo-sql'
    container_name: mysql
  backend:
    image: my-app
    build: ./api-build
    container_name: demo-api
    networks:
      - demo-net
    hostname: 'demo-api'
    ports:
      - '8080:8080'
    expose:
      - '8080'
  frontend:
    image: angular-app
    build: ./angular-build
    container_name: my-front
    networks:
      - demo-net
    hostname: 'my-front'
    ports:
      - '8081:80'
    expose:
      - '80'
volumes:
  my-volume:
    external: true
networks:
  demo-net:
    external: true
